### PR TITLE
Enable Layout/IndentHash

### PR DESCRIPTION
**Pull request by gmcquistin**
Pls.

### CODE REVIEW

**Comment by rdallasgray** [comment]
It screws up formatting when the hash is a method argument, unfortunately. Hang on I'll give an example.

**Comment by rdallasgray** [comment]
See here https://github.com/bbatsov/rubocop/issues/3803

**Comment by gmcquistin** [comment]
Is that the same thing? AlignHash vs IndentHash?

**Comment by gmcquistin** [comment]
Before:

```
let(:attributes) {
  {
    facilities: %w{car_wash toilet},
    products: %w{ultimate_diesel},
    geo_world_country: GeoWorldCountry.uk
} }
```
After
```
let(:attributes) do
  {
    facilities: %w{car_wash toilet},
    products: %w{ultimate_diesel},
    geo_world_country: GeoWorldCountry.uk
  }
end
```

**Comment by rdallasgray** [comment]
If I turn on `Layout/IndentHash`, I get the issue I mentioned, so I'd prefer it be kept off for now. 

I think we need to understand that this won't *ever* get us auto-formatting on a par with Prettier -- we need to put work in upfront. Something like:
```ruby
let(:something) { {
  test: "test"
  other: "other"
} }
```
... is just bad Ruby style, and needs to be manually corrected before any attempt at auto-formatting.

**Comment by gmcquistin** [comment]
agreed - this isn't quite a panacea, but close enough :)

**Comment by rdallasgray** [comment]
Nb we can enable this if we use:
```yaml
Layout/AlignHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_implicit
```

**Comment by gmcquistin** [comment]
let's do that! :D

**Pull request closed without merging**
